//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsw2026Tpi.CrossCutting.Resources
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsw2026Tpi.CrossCutting.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El turno seleccionado ya no se encuentra disponible.
        /// </summary>
        public static string APPOINTMENT_CONFLICT
        {
            get
            {
                return ResourceManager.GetString("APPOINTMENT_CONFLICT", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden reservar turnos en fechas u horarios pasados.
        /// </summary>
        public static string APPOINTMENT_PAST_DATE
        {
            get
            {
                return ResourceManager.GetString("APPOINTMENT_PAST_DATE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        public static string AUTHENTICATION_FAILED
        {
            get
            {
                return ResourceManager.GetString("AUTHENTICATION_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Se requieren permisos para la operación solicitada.
        /// </summary>
        public static string AUTHORIZATION_FAILED
        {
            get
            {
                return ResourceManager.GetString("AUTHORIZATION_FAILED", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El turno seleccionado no se encuentra disponible.
        /// </summary>
        public static string AVAILABILITY_SLOT_NOT_AVAILABLE
        {
            get
            {
                return ResourceManager.GetString("AVAILABILITY_SLOT_NOT_AVAILABLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El turno no se encuentra reservado.
        /// </summary>
        public static string AVAILABILITY_SLOT_NOT_BOOKED
        {
            get
            {
                return ResourceManager.GetString("AVAILABILITY_SLOT_NOT_BOOKED", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar la disponibilidad porque hay turnos reservados.
        /// </summary>
        public static string AVAILABILITY_BOOKED_SLOTS {
            get {
                return ResourceManager.GetString("AVAILABILITY_BOOKED_SLOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los horarios se solapan con una disponibilidad existente .
        /// </summary>
        public static string AVAILABILITY_OVERLAP {
            get {
                return ResourceManager.GetString("AVAILABILITY_OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible cancelar el turno.
        /// </summary>
        public static string CANCEL_APPOINTMENT
        {
            get
            {
                return ResourceManager.GetString("CANCEL_APPOINTMENT", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La entidad {0} no se encontró.
        /// </summary>
        public static string ENTITY_NOTFOUND
        {
            get
            {
                return ResourceManager.GetString("ENTITY_NOTFOUND", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a DNI inválido, debe tener entre 7 y 8 dígitos.
        /// </summary>
        public static string PATIENT_INVALID_DNI
        {
            get
            {
                return ResourceManager.GetString("PATIENT_INVALID_DNI", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al registrar el usuario.
        /// </summary>
        public static string REGISTER_USER_CONFLICT
        {
            get
            {
                return ResourceManager.GetString("REGISTER_USER_CONFLICT", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Datos de registración de usuario no válidos.
        /// </summary>
        public static string REGISTER_USER_INVALID
        {
            get
            {
                return ResourceManager.GetString("REGISTER_USER_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error no controlado.
        /// </summary>
        public static string UNHANDLED_ERROR
        {
            get
            {
                return ResourceManager.GetString("UNHANDLED_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más errores de validación ocurrieron.
        /// </summary>
        public static string VALIDATION_ERROR
        {
            get
            {
                return ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);
            }
        }
    }
}
